name:               "yensama"
description:        "Guitar&Code&You"

url:                ""
author:             "yensama"
email:              "yuanchen0xi@126.com"
gravatar_hash:      "0a9f6fbed4d65ae31cd230ba0b10bb96"
twitter:            ""
email:              "yuanchen0xi@126.com"
github:             "yensama3"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "yensama"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5420.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate